apiVersion: v2
name: qnap-trident
description: A Helm chart for deploying Trident CSI Plugin using Trident Operator
type: application
version: 2.0.0
kubeVersion: ">= 1.24.0 <= 1.30"
appVersion: 1.3.0
