# Default values for qnap-trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

tridentOperator:
  image: qnapsystem/qnap-csi-operator:v1.2.0
  cgiServerImage : qnapsystem/qnap-csi-backend-qts-sidecar:v1.2.0
  imagePullPolicy: IfNotPresent
  logLevel: debug

tridentOrchestrator:
  image: qnapsystem/qnap-csi:v1.2.0
  debug: true