# Default values for qnap-trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

tridentOperator:
  image: davidcheng0922/grpc-server:v1.3.0-dev
  cgiServerImage : davidcheng0922/trident-operator:v1.3.0-dev-test
  imagePullPolicy: IfNotPresent
  logLevel: debug

tridentOrchestrator:
  image: davidcheng0922/qnap-csi:v1.3.0-dev-test
  debug: true