apiVersion: v1
kind: Secret
metadata:
    name: qts-csi-smb #Required. Name your secert for Samba.
    namespace: trident
type: Opaque
stringData:
    username: user1 #Required. The valid Samba username on the NAS.
    password: 0000 #Required. The valid Samba password on the NAS.