kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-premium-hero
  annotations:
    # thin allocate is customized
    trident.qnap.io/ThinAllocate: "false"

    # QuTS-hero features
    trident.qnap.io/Deduplication: "true"
    trident.qnap.io/Compression: "true"
    trident.qnap.io/FastClone: "true"

    # I/O synchronization mode: default, sync, or async
    # On QuTS hero these map to ZIL synchronized I/O mode Auto, Always, and None.
    # trident.qnap.io/IoSyncMode: "default"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: premium
