kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-import-blk
  namespace: default
  annotations:
    trident.qnap.io/importOriginalName: "LUN_0"
    trident.qnap.io/importBackendName: "hero"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium
