apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-label
  template:
    metadata:
      labels:
          app: demo-label
    spec:
      containers:
        - name: demo-pod
          image: davidcheng0922/docker-demo
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-pvc
              mountPath: "/demo"
      volumes:
      - name: my-pvc
        persistentVolumeClaim:
          claimName: pvc-file
