kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  annotations: # Required. Define features for your volume.
    trident.qnap.io/threshold: "90"
    trident.qnap.io/ThinAllocate: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storageclass1 # Required. Corresponds to the StorageClass name.