kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-standard
  annotations:
    # thin allocate is customized
    trident.qnap.io/ThinAllocate: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
