apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-clone
spec:
  accessModes:
    - ReadWriteOnce # iSCSI: ReadWriteOnce, Samba: ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-sample
  storageClassName: storageclass1
