apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass1 
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=performance1" # Required. Corresponds to the labels in the virtual pool.
allowVolumeExpansion: true