apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid0
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=raid0"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid1
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=raid1"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid5
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=raid5"
allowVolumeExpansion: true