apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass1 # Required. Name your storageclass.
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=performance1" # Required. Corresponds to the labels in the virtual pool.
  trident.qnap.io/fileProtocol: "smb"        
  csi.storage.k8s.io/node-stage-secret-name: "qts-csi-smb" # Required. It must match the metadata.name in the Secret file.       
  csi.storage.k8s.io/node-stage-secret-namespace: "trident" # Required. It must match the metadata.namespace in the Secret file.  
allowVolumeExpansion: true