apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-clone-file
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-file
  storageClassName: qts-smb

