apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-clone-snap-file
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: pvc-snapshot-file
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: qts-smb

