kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-from-snap-blk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: pvc-snapshot-premium
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium